[mongodb]
mongodb-dev.pavanreddy.online

[catalogue]
catalogue-dev.pavanreddy.online

[redis]
redis-dev.pavanreddy.online

[user]
user-dev.pavanreddy.online

[cart]
cart-dev.pavanreddy.online

[mysql]
mysql-dev.pavanreddy.online

[shipping]
shipping-dev.pavanreddy.online

[rabbitmq]
rabbitmq-dev.pavanreddy.online

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321
MONGODB_HOST=mongodb-dev.pavanreddy.online
