- name: create ec2 and r53 records
  hosts: all
  connection: local
  vars:
    sg_id: sg-095a9a8243a52d49f
    ami_id: ami-0220d79f3f480ecf5
    domain_name: pavanreddy.online
    env: dev
    instances:
    - mongodb
    - catalogue
  tasks: 
   - name: create ec2 instance
     amazon.aws.ec2_instance:  
        instance_type: "t3.micro"
        security_group: "{{ sg_id }}"
        image_id: "{{ ami_id }}"
        name: "{{ item }} - {{ env }}"
        tags:
          Project: roboshop
          Component: "{{ item }}" 
          Environment: "{{ env }}"
          Name: "{{ item }} - {{ env }}"
     loop: "{{ instances }}"
     register: ec2_output #to see the output of ec2 instance creation

   - name: print the output
     ansible.builtin.debug:
        msg: "{{ ec2_output }}"

   - name: create r53 record for each instance
     amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}" 
      record: "{{ item.item }}-{{ env }}.{{ domain_name }}" #mongodb-dev.pavanreddy.online
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true
     loop: "{{ ec2_output.results }}"